// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Email struct {
	To                   string               `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Subject              string               `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Message              string               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Email) Reset()         { *m = Email{} }
func (m *Email) String() string { return proto.CompactTextString(m) }
func (*Email) ProtoMessage()    {}
func (*Email) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Email) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Email.Unmarshal(m, b)
}
func (m *Email) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Email.Marshal(b, m, deterministic)
}
func (m *Email) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Email.Merge(m, src)
}
func (m *Email) XXX_Size() int {
	return xxx_messageInfo_Email.Size(m)
}
func (m *Email) XXX_DiscardUnknown() {
	xxx_messageInfo_Email.DiscardUnknown(m)
}

var xxx_messageInfo_Email proto.InternalMessageInfo

func (m *Email) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Email) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Email) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Email) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Email) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type CreateEmailResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEmailResponse) Reset()         { *m = CreateEmailResponse{} }
func (m *CreateEmailResponse) String() string { return proto.CompactTextString(m) }
func (*CreateEmailResponse) ProtoMessage()    {}
func (*CreateEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *CreateEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmailResponse.Unmarshal(m, b)
}
func (m *CreateEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmailResponse.Marshal(b, m, deterministic)
}
func (m *CreateEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmailResponse.Merge(m, src)
}
func (m *CreateEmailResponse) XXX_Size() int {
	return xxx_messageInfo_CreateEmailResponse.Size(m)
}
func (m *CreateEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmailResponse proto.InternalMessageInfo

func (m *CreateEmailResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CreateEmailResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Email)(nil), "api.Email")
	proto.RegisterType((*CreateEmailResponse)(nil), "api.CreateEmailResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x41, 0x4f, 0x83, 0x40,
	0x10, 0x85, 0x03, 0x2d, 0x1a, 0xa6, 0xc6, 0xc3, 0x78, 0xd9, 0x70, 0xb1, 0xe9, 0xa9, 0xa7, 0x6d,
	0xd2, 0x5e, 0xbc, 0x1a, 0x62, 0xe2, 0x99, 0xe8, 0x0f, 0x58, 0xca, 0x48, 0x30, 0xd0, 0xd9, 0xb0,
	0xd3, 0xdf, 0xe7, 0x5f, 0x33, 0x0c, 0x45, 0x31, 0x31, 0xe9, 0xed, 0xbd, 0x99, 0xf7, 0xe0, 0x9b,
	0x85, 0xd4, 0xf9, 0xc6, 0xfa, 0x9e, 0x85, 0x71, 0xe1, 0x7c, 0x93, 0x3d, 0xd6, 0xcc, 0x75, 0x4b,
	0x3b, 0x1d, 0x95, 0xe7, 0x8f, 0x9d, 0x34, 0x1d, 0x05, 0x71, 0x9d, 0x1f, 0x53, 0x9b, 0xaf, 0x08,
	0x92, 0x97, 0xce, 0x35, 0x2d, 0xde, 0x43, 0x2c, 0x6c, 0xa2, 0x75, 0xb4, 0x4d, 0x8b, 0x58, 0x18,
	0x0d, 0xdc, 0x86, 0x73, 0xf9, 0x49, 0x47, 0x31, 0xb1, 0x0e, 0x27, 0x3b, 0x6c, 0x3a, 0x0a, 0xc1,
	0xd5, 0x64, 0x16, 0xe3, 0xe6, 0x62, 0xf1, 0x09, 0xd2, 0x77, 0x5f, 0x39, 0xa1, 0xea, 0x59, 0xcc,
	0x72, 0x1d, 0x6d, 0x57, 0xfb, 0xcc, 0x8e, 0x08, 0x76, 0x42, 0xb0, 0x6f, 0x13, 0x42, 0xf1, 0x1b,
	0x1e, 0x9a, 0x79, 0x4f, 0x97, 0x66, 0x72, 0xbd, 0xf9, 0x13, 0xde, 0xe4, 0xf0, 0x30, 0x1a, 0x3d,
	0xa3, 0xa0, 0xe0, 0xf9, 0x14, 0x08, 0x11, 0x96, 0x47, 0xae, 0x48, 0x0f, 0x4a, 0x0a, 0xd5, 0x73,
	0xf0, 0xf8, 0x0f, 0xf8, 0x3e, 0x87, 0x3b, 0xad, 0xbf, 0xba, 0x53, 0xd5, 0x52, 0x8f, 0x07, 0x58,
	0xcd, 0x3e, 0x8a, 0x60, 0x87, 0x77, 0x55, 0x9d, 0x19, 0xd5, 0xff, 0xfc, 0xb2, 0xbc, 0x51, 0xd0,
	0xc3, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe5, 0x09, 0x89, 0xdb, 0x85, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmailHandlerClient is the client API for EmailHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmailHandlerClient interface {
	CreateEmail(ctx context.Context, in *Email, opts ...grpc.CallOption) (*CreateEmailResponse, error)
}

type emailHandlerClient struct {
	cc *grpc.ClientConn
}

func NewEmailHandlerClient(cc *grpc.ClientConn) EmailHandlerClient {
	return &emailHandlerClient{cc}
}

func (c *emailHandlerClient) CreateEmail(ctx context.Context, in *Email, opts ...grpc.CallOption) (*CreateEmailResponse, error) {
	out := new(CreateEmailResponse)
	err := c.cc.Invoke(ctx, "/api.EmailHandler/CreateEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailHandlerServer is the server API for EmailHandler service.
type EmailHandlerServer interface {
	CreateEmail(context.Context, *Email) (*CreateEmailResponse, error)
}

func RegisterEmailHandlerServer(s *grpc.Server, srv EmailHandlerServer) {
	s.RegisterService(&_EmailHandler_serviceDesc, srv)
}

func _EmailHandler_CreateEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Email)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailHandlerServer).CreateEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EmailHandler/CreateEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailHandlerServer).CreateEmail(ctx, req.(*Email))
	}
	return interceptor(ctx, in, info, handler)
}

var _EmailHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.EmailHandler",
	HandlerType: (*EmailHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEmail",
			Handler:    _EmailHandler_CreateEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
