// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateEmailRequest struct {
	To                   string               `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Subject              string               `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Message              string               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateEmailRequest) Reset()         { *m = CreateEmailRequest{} }
func (m *CreateEmailRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEmailRequest) ProtoMessage()    {}
func (*CreateEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *CreateEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmailRequest.Unmarshal(m, b)
}
func (m *CreateEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmailRequest.Marshal(b, m, deterministic)
}
func (m *CreateEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmailRequest.Merge(m, src)
}
func (m *CreateEmailRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEmailRequest.Size(m)
}
func (m *CreateEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmailRequest proto.InternalMessageInfo

func (m *CreateEmailRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *CreateEmailRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *CreateEmailRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateEmailRequest) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *CreateEmailRequest) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type CreateEmailResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEmailResponse) Reset()         { *m = CreateEmailResponse{} }
func (m *CreateEmailResponse) String() string { return proto.CompactTextString(m) }
func (*CreateEmailResponse) ProtoMessage()    {}
func (*CreateEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *CreateEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmailResponse.Unmarshal(m, b)
}
func (m *CreateEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmailResponse.Marshal(b, m, deterministic)
}
func (m *CreateEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmailResponse.Merge(m, src)
}
func (m *CreateEmailResponse) XXX_Size() int {
	return xxx_messageInfo_CreateEmailResponse.Size(m)
}
func (m *CreateEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmailResponse proto.InternalMessageInfo

func (m *CreateEmailResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CreateEmailResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetEmailRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEmailRequest) Reset()         { *m = GetEmailRequest{} }
func (m *GetEmailRequest) String() string { return proto.CompactTextString(m) }
func (*GetEmailRequest) ProtoMessage()    {}
func (*GetEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *GetEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmailRequest.Unmarshal(m, b)
}
func (m *GetEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmailRequest.Marshal(b, m, deterministic)
}
func (m *GetEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmailRequest.Merge(m, src)
}
func (m *GetEmailRequest) XXX_Size() int {
	return xxx_messageInfo_GetEmailRequest.Size(m)
}
func (m *GetEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmailRequest proto.InternalMessageInfo

func (m *GetEmailRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetEmailResponse struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	To                   string               `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Subject              string               `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Message              string               `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetEmailResponse) Reset()         { *m = GetEmailResponse{} }
func (m *GetEmailResponse) String() string { return proto.CompactTextString(m) }
func (*GetEmailResponse) ProtoMessage()    {}
func (*GetEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *GetEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmailResponse.Unmarshal(m, b)
}
func (m *GetEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmailResponse.Marshal(b, m, deterministic)
}
func (m *GetEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmailResponse.Merge(m, src)
}
func (m *GetEmailResponse) XXX_Size() int {
	return xxx_messageInfo_GetEmailResponse.Size(m)
}
func (m *GetEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmailResponse proto.InternalMessageInfo

func (m *GetEmailResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetEmailResponse) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *GetEmailResponse) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *GetEmailResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetEmailResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *GetEmailResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateEmailRequest)(nil), "api.CreateEmailRequest")
	proto.RegisterType((*CreateEmailResponse)(nil), "api.CreateEmailResponse")
	proto.RegisterType((*GetEmailRequest)(nil), "api.GetEmailRequest")
	proto.RegisterType((*GetEmailResponse)(nil), "api.GetEmailResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x4d, 0x4e, 0xeb, 0x30,
	0x14, 0x85, 0x65, 0xb7, 0xe9, 0x6b, 0x5d, 0xbd, 0x1f, 0xb9, 0x0f, 0x11, 0x45, 0x48, 0x94, 0x8c,
	0x2a, 0x06, 0x89, 0x28, 0x03, 0x10, 0x33, 0x54, 0x21, 0xe6, 0x11, 0x5d, 0x80, 0xdb, 0x5c, 0x2a,
	0xa3, 0x26, 0x36, 0xf5, 0xed, 0x06, 0xd8, 0x02, 0x03, 0x36, 0xc5, 0x8c, 0x19, 0x63, 0x16, 0x82,
	0x62, 0x27, 0xb4, 0x4d, 0xf9, 0x11, 0xcc, 0xe2, 0x7b, 0xce, 0x89, 0xcf, 0xfd, 0x64, 0xd6, 0x11,
	0x5a, 0x46, 0x7a, 0xa1, 0x50, 0xf1, 0x86, 0xd0, 0x32, 0xd8, 0x9f, 0x29, 0x35, 0x9b, 0x43, 0x6c,
	0x47, 0x93, 0xe5, 0x75, 0x8c, 0x32, 0x03, 0x83, 0x22, 0xd3, 0xce, 0x15, 0xec, 0x95, 0x06, 0xa1,
	0x65, 0x2c, 0xf2, 0x5c, 0xa1, 0x40, 0xa9, 0x72, 0xe3, 0xd4, 0xf0, 0x91, 0x30, 0x3e, 0x5a, 0x80,
	0x40, 0xb8, 0xc8, 0x84, 0x9c, 0x27, 0x70, 0xbb, 0x04, 0x83, 0xfc, 0x0f, 0xa3, 0xa8, 0x7c, 0xd2,
	0x27, 0x83, 0x4e, 0x42, 0x51, 0x71, 0x9f, 0xfd, 0x32, 0xcb, 0xc9, 0x0d, 0x4c, 0xd1, 0xa7, 0x76,
	0x58, 0x1d, 0x0b, 0x25, 0x03, 0x63, 0xc4, 0x0c, 0xfc, 0x86, 0x53, 0xca, 0x23, 0x3f, 0x65, 0x9d,
	0xb1, 0x4e, 0x05, 0x42, 0x7a, 0x8e, 0x7e, 0xb3, 0x4f, 0x06, 0xdd, 0x61, 0x10, 0xb9, 0x32, 0x51,
	0xd5, 0x36, 0xba, 0xaa, 0xda, 0x26, 0x2b, 0x73, 0x91, 0x74, 0x9d, 0x8a, 0xa4, 0xf7, 0x75, 0xf2,
	0xcd, 0x1c, 0x8e, 0x58, 0x6f, 0x63, 0x1b, 0xa3, 0x55, 0x6e, 0x80, 0x73, 0xd6, 0x9c, 0xaa, 0x14,
	0xec, 0x42, 0x5e, 0x62, 0xbf, 0xd7, 0x8b, 0xd3, 0x8d, 0xe2, 0xe1, 0x01, 0xfb, 0x7b, 0x09, 0x58,
	0xe7, 0x21, 0xd3, 0x32, 0x4e, 0x65, 0x1a, 0x3e, 0x13, 0xf6, 0x6f, 0xe5, 0x29, 0x6f, 0xa9, 0x99,
	0x4a, 0x88, 0xf4, 0x3d, 0x88, 0x8d, 0x0f, 0x21, 0x36, 0x3f, 0x81, 0xe8, 0xfd, 0x18, 0x62, 0xeb,
	0x1b, 0x10, 0x87, 0x0f, 0x84, 0x79, 0x76, 0x33, 0x3e, 0x66, 0xdd, 0x35, 0x9c, 0x7c, 0x37, 0x2a,
	0x1e, 0xdf, 0xf6, 0x73, 0x09, 0xfc, 0x6d, 0xc1, 0x31, 0x09, 0x7b, 0x77, 0x4f, 0x2f, 0xf7, 0xf4,
	0x77, 0xd8, 0x8e, 0x8f, 0x62, 0x28, 0x94, 0x33, 0x72, 0xc8, 0x4f, 0x58, 0xbb, 0x82, 0xc7, 0xff,
	0xdb, 0x68, 0x8d, 0x77, 0xb0, 0x53, 0x9b, 0xba, 0xbf, 0x4d, 0x5a, 0xb6, 0xf8, 0xf1, 0x6b, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x81, 0x0c, 0x4d, 0x36, 0x05, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmailClient is the client API for Email service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmailClient interface {
	CreateEmail(ctx context.Context, in *CreateEmailRequest, opts ...grpc.CallOption) (*CreateEmailResponse, error)
	GetEmail(ctx context.Context, in *GetEmailRequest, opts ...grpc.CallOption) (*GetEmailResponse, error)
}

type emailClient struct {
	cc *grpc.ClientConn
}

func NewEmailClient(cc *grpc.ClientConn) EmailClient {
	return &emailClient{cc}
}

func (c *emailClient) CreateEmail(ctx context.Context, in *CreateEmailRequest, opts ...grpc.CallOption) (*CreateEmailResponse, error) {
	out := new(CreateEmailResponse)
	err := c.cc.Invoke(ctx, "/api.Email/CreateEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) GetEmail(ctx context.Context, in *GetEmailRequest, opts ...grpc.CallOption) (*GetEmailResponse, error) {
	out := new(GetEmailResponse)
	err := c.cc.Invoke(ctx, "/api.Email/GetEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailServer is the server API for Email service.
type EmailServer interface {
	CreateEmail(context.Context, *CreateEmailRequest) (*CreateEmailResponse, error)
	GetEmail(context.Context, *GetEmailRequest) (*GetEmailResponse, error)
}

func RegisterEmailServer(s *grpc.Server, srv EmailServer) {
	s.RegisterService(&_Email_serviceDesc, srv)
}

func _Email_CreateEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).CreateEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Email/CreateEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).CreateEmail(ctx, req.(*CreateEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_GetEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).GetEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Email/GetEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).GetEmail(ctx, req.(*GetEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Email_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Email",
	HandlerType: (*EmailServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEmail",
			Handler:    _Email_CreateEmail_Handler,
		},
		{
			MethodName: "GetEmail",
			Handler:    _Email_GetEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
